import pandas as pd
df=pd.read_csv('bestsellers_with_categories.csv')
#df.drop_duplicates() to remove double entries. By default, it considers all the columns to identify duplicates. If you want to consider specific columns, you can use the subset parameter. For example, df.drop_duplicates(subset=['Name', 'Author']) will remove duplicates based on the 'Name' and 'Author' columns.
#By default, it keeps the first occurrence of the duplicate and removes the rest. If you want to keep the last occurrence, you can use the keep parameter. For example, df.drop_duplicates(keep='last') will keep the last occurrence of the duplicate and remove the rest.
#If you want to remove all duplicates and keep only unique rows, you can set the keep parameter to False. For example, df.drop_duplicates(keep=False) will remove all duplicates and keep only unique rows.
print(df.drop_duplicates())#remove duplicates and print the resulting DataFrame
df.to_csv('bestsellers_with_categories_no_duplicates.csv', index=False)#save the resulting DataFrame to a new CSV file without the index column
#Note: df.drop_duplicates() does not modify the original DataFrame unless you set the inplace parameter to True. If you want to modify the original DataFrame, you can use df.drop_duplicates(inplace=True).
#note: df.fillna() is used to fill missing values in a DataFrame. By default, it fills missing values with NaN. You can specify a value to fill the missing values using the value parameter. For example, df.fillna(0) will fill all missing values with 0. You can also specify a method to fill the missing values using the method parameter. For example, df.fillna(method='ffill') will fill missing values using the forward fill method, which propagates the last valid observation forward.
# Note: df.fillna() does not modify the original DataFrame unless you set the inplace parameter to True. If you want to modify the original DataFrame, you can use df.fillna(inplace=True).
# Note: df.drop_duplicates() and df.fillna() are just two of the many functions available in pandas for data cleaning and preprocessing. Depending on your specific use case, you may need to use other functions such as df.dropna(), df.replace(), or df.astype() to further clean and preprocess your data.
# dropna() is used to remove missing values from a DataFrame. By default, it removes any row that contains at least one missing value. You can specify the axis parameter to remove columns instead of rows. For example, df.dropna(axis=1) will remove any column that contains at least one missing value. You can also specify the how parameter to determine how to drop rows or columns. For example, df.dropna(how='all') will only drop rows or columns that contain all missing values.
# Note: df.dropna() does not modify the original DataFrame unless you set the inplace parameter to True. If you want to modify the original DataFrame, you can use df.dropna(inplace=True). 